# Generated by Django 3.0.5 on 2020-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytown',
            name='is_city',
            field=models.BooleanField(),
        ),
    ]
