# Generated by Django 3.0.5 on 2020-08-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citytown',
            options={'verbose_name': 'CityTown', 'verbose_name_plural': 'CityTowns'},
        ),
        migrations.AddField(
            model_name='citytown',
            name='is_city',
            field=models.BooleanField(default=False),
        ),
    ]
